stages:
  - validate
  - dev
  - prod

validate:
  stage: validate
  script:
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY
    - echo $AWS_DEFAULT_REGION
    - echo $CI_JOB_ID
    - export
    - terraform --version
    - echo "------------------------- Terraform validate Init -----------------------"
    - terraform init
    - terraform validate

dev_plan:
  stage: dev
  environment:
    name: dev
  only:
    - /^dev$/
  script:
    - echo "Building..... terraform plan"
    - terraform init
    - terraform plan

apply dev:
  stage: dev
  environment:
    name: dev
  script:
    - terraform init
    - terraform apply -auto-approve
  dependencies:
    - dev_plan
  only:
   - /^dev$/

##Prod
prd_plan:
  stage: prod
  environment:
    name: prd
  only:
    - /^master$/
  script:
    - echo "Building..... terraform plan"
    - terraform init
    - terraform plan

apply prd:
  stage: prod
  environment:
    name: prd
  only:
    - /^master$/
  script:
    - echo ".....in Production"
    - terraform init
    - terraform apply -auto-approve
  when: manual