name: Terraform PLAN
on:
   push:
      branches:
        - dev
env:
  TF_LOG: INFO
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@main
        with:
          image-tag: 'latest'
          install-awslocal: 'true' 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform Workflow
        working-directory: examples/
        run: |
          tflocal init
          tflocal plan